global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'producer'
    scrape_interval: 1s
    metrics_path: /metrics

    dns_sd_configs:
      - names:
          - "producer"
        type: A
        port: 8000